services:
    _defaults:
        autowire: true
        autoconfigure: true 
    spygar_index_controller:
        public: true
        class: Spygar\FruityBundle\Controller\IndexController
        arguments:
            - '@spygar.fruits.repositroy'
            - '@spygar.family.repositroy'